# Generated by Django 5.0.2 on 2026-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Account approved by administrator', verbose_name='Approved'),
        ),
    ]
