# Generated by Django 5.0.2 on 2026-04-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Base URL of the Odoo instance, e.g., https://odoo.albacapital.co.ke', verbose_name='Odoo URL')),
                ('api_key', models.CharField(help_text='X-Alba-API-Key for authenticating with Odoo', max_length=255, verbose_name='API Key')),
                ('database', models.CharField(blank=True, help_text='Odoo database name (optional)', max_length=100, verbose_name='Database')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for verifying webhook signatures', max_length=255, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('error', 'Error')], default='unknown', max_length=20, verbose_name='Connection Status')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odoo_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odoo Configuration',
                'verbose_name_plural': 'Odoo Configuration',
                'db_table': 'odoo_config',
            },
        ),
    ]
