# Generated by Django 5.0.2 on 2026-04-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_odoo_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooconfig',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL where Odoo sends webhooks (e.g., https://yourdomain.com/api/v1/webhooks/odoo/)', verbose_name='Outbound Webhook URL'),
        ),
    ]
