# Generated by Django 6.0.2 on 2026-02-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, help_text='URL path of the request', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Django session key', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent string', null=True),
        ),
    ]
