# Generated by Django 6.0.2 on 2026-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_request_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_mfa_verification',
            field=models.DateTimeField(blank=True, help_text='Last successful MFA verification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Backup codes for MFA recovery'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='MFA enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', help_text='TOTP secret key', max_length=32),
        ),
    ]
