# Generated by Django 5.0.2 on 2026-03-02 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_statement_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/bank_statements/%Y/%m/%d/', verbose_name='Bank Statement'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_statement_verified',
            field=models.BooleanField(default=False, verbose_name='Bank Statement Verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='face_encoding_data',
            field=models.TextField(blank=True, null=True, verbose_name='Face Encoding Data'),
        ),
        migrations.AddField(
            model_name='customer',
            name='face_recognition_photo',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/face_photos/%Y/%m/%d/', verbose_name='Face Recognition Photo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='face_recognition_verified',
            field=models.BooleanField(default=False, verbose_name='Face Recognition Verified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='face_scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Face Scan Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/national_id/%Y/%m/%d/', verbose_name='National ID Document'),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id_verified',
            field=models.BooleanField(default=False, verbose_name='National ID Verified'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['national_id_verified', 'bank_statement_verified', 'face_recognition_verified'], name='customers_nationa_7521e0_idx'),
        ),
    ]
