# Generated by Django 5.0.2

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_customer_bank_statement_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="Installment #"),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "principal_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Principal Due",
                    ),
                ),
                (
                    "interest_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Interest Due",
                    ),
                ),
                (
                    "fees_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Fees Due",
                    ),
                ),
                (
                    "penalty_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Penalty Due",
                    ),
                ),
                (
                    "total_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Total Due",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Amount Paid",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Paid")),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="Date Paid"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "odoo_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the corresponding record in Odoo",
                        max_length=50,
                        verbose_name="Odoo Record ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repayment Schedule",
                "verbose_name_plural": "Repayment Schedules",
                "db_table": "repayment_schedule",
                "ordering": ["loan", "installment_number"],
                "indexes": [
                    models.Index(
                        fields=["loan", "due_date"],
                        name="repayment_s_loan_id_duedate_idx",
                    ),
                    models.Index(
                        fields=["is_paid", "due_date"],
                        name="repayment_s_is_paid_duedate_idx",
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="repaymentschedule",
            unique_together={("loan", "installment_number")},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("APPLICATION_UNDER_REVIEW", "Application Under Review"),
                            ("APPLICATION_APPROVED", "Application Approved"),
                            ("APPLICATION_REJECTED", "Application Rejected"),
                            ("LOAN_DISBURSED", "Loan Disbursed"),
                            ("PAYMENT_DUE", "Payment Due"),
                            ("PAYMENT_OVERDUE", "Payment Overdue"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("KYC_VERIFIED", "KYC Verified"),
                            ("KYC_REJECTED", "KYC Rejected"),
                            ("ACCOUNT_APPROVED", "Account Approved"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("SYSTEM", "System"), ("ODOO", "Odoo")],
                        default="SYSTEM",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_isread_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notificatio_user_type_idx",
                    ),
                ],
            },
        ),
    ]
