# Generated by Django 5.0.2 on 2026-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_notification_repaymentschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_c4e471_idx',
            old_name='notificatio_user_isread_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_63f199_idx',
            old_name='notificatio_user_type_idx',
        ),
        migrations.RenameIndex(
            model_name='repaymentschedule',
            new_name='repayment_s_loan_id_762656_idx',
            old_name='repayment_s_loan_id_duedate_idx',
        ),
        migrations.RenameIndex(
            model_name='repaymentschedule',
            new_name='repayment_s_is_paid_2ebb1d_idx',
            old_name='repayment_s_is_paid_duedate_idx',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='is_fee_based',
            field=models.BooleanField(default=False, help_text='Bid bonds and performance bonds are fee-based, not interest-bearing', verbose_name='Is Fee-based Product'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='category',
            field=models.CharField(choices=[('salary_advance', 'Salary Advance'), ('business_loan', 'Business Loan'), ('personal_loan', 'Personal Loan'), ('ipf_loan', 'IPF Loan'), ('bid_bond', 'Bid Bond'), ('performance_bond', 'Performance Bond'), ('staff_loan', 'Staff Loan'), ('asset_financing', 'Asset Financing')], max_length=30, verbose_name='Category'),
        ),
    ]
