# Generated by Django 6.0.3 on 2026-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_notificatio_user_isread_idx_notificatio_user_id_c4e471_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='odoo_application_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Odoo Application ID'),
        ),
    ]
