# Generated by Django 5.0.2 on 2026-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanapplication_odoo_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID/Passport Number'),
        ),
    ]
