# Generated by Django 5.0.2 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_odoo_integration_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhook_del_event_t_e3b305_idx',
            old_name='wh_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhook_del_status_709229_idx',
            old_name='wh_status_idx',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='odoo_loan_number',
            field=models.CharField(blank=True, help_text='Odoo loan reference number (e.g. LN-20240601-0001)', max_length=50, verbose_name='Odoo Loan Number'),
        ),
    ]
