# Generated by Django 5.2.8 on 2026-05-04 08:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_rename_wh_event_type_idx_webhook_del_event_t_e3b305_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Annual Turnover'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Industry/Sector'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Business Registration Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_business_entity',
            field=models.BooleanField(default=False, verbose_name='Is Business Entity'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Annual Turnover'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Business Registration Number'),
        ),
    ]
