# Generated by Django 5.2.12 on 2026-05-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_customer_annual_turnover_customer_business_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('AGENT', 'Agent'), ('STAFF', 'Staff'), ('DIRECTOR', 'Director')], help_text='How the customer was referred to Alba Capital', max_length=20, null=True, verbose_name='Referral Source'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Sector Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Sector Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='sectors_code_9c3b36_idx'), models.Index(fields=['is_active'], name='sectors_is_acti_1f0448_idx')],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='loans.sector'),
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Subsector Name')),
                ('code', models.CharField(max_length=50, verbose_name='Subsector Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsectors', to='loans.sector')),
            ],
            options={
                'verbose_name': 'Subsector',
                'verbose_name_plural': 'Subsectors',
                'db_table': 'subsectors',
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='loans.subsector'),
        ),
        migrations.AddIndex(
            model_name='subsector',
            index=models.Index(fields=['sector', 'is_active'], name='subsectors_sector__81d842_idx'),
        ),
        migrations.AddIndex(
            model_name='subsector',
            index=models.Index(fields=['code'], name='subsectors_code_7bde96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subsector',
            unique_together={('sector', 'code')},
        ),
    ]
