# Generated by Django for Phase 1 Odoo Alignment

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_customer_referral_source_sector_customer_sector_and_more'),
    ]

    operations = [
        # ========================================
        # Location Models (Hierarchical)
        # ========================================
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='County Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='County Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub-County Name')),
                ('code', models.CharField(max_length=10, verbose_name='Sub-County Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_counties', to='loans.county')),
            ],
            options={
                'verbose_name': 'Sub-County',
                'verbose_name_plural': 'Sub-Counties',
                'ordering': ['county', 'name'],
                'db_table': 'sub_counties',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ward Name')),
                ('code', models.CharField(max_length=10, verbose_name='Ward Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='loans.subcounty')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['sub_county', 'name'],
                'db_table': 'wards',
            },
        ),
        
        # ========================================
        # Customer Model Enhancements
        # ========================================
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NATIONAL', 'National ID'),
                    ('PASSPORT', 'Passport'),
                    ('MILITARY', 'Military ID'),
                    ('OTHER', 'Other'),
                ],
                help_text='Type of identification document',
                max_length=20,
                verbose_name='ID Type'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MALE', 'Male'),
                    ('FEMALE', 'Female'),
                    ('OTHER', 'Other'),
                ],
                max_length=10,
                verbose_name='Gender'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SINGLE', 'Single'),
                    ('MARRIED', 'Married'),
                    ('DIVORCED', 'Divorced'),
                    ('WIDOWED', 'Widowed'),
                ],
                max_length=20,
                verbose_name='Marital Status'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(default='Kenyan', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customer',
            name='months_employed',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Number of months in current employment',
                null=True,
                verbose_name='Months in Current Employment'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_income',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Additional monthly income from other sources',
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Other Monthly Income'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SOLE_PROPRIETOR', 'Sole Proprietor'),
                    ('PARTNERSHIP', 'Partnership'),
                    ('LIMITED_COMPANY', 'Limited Company'),
                    ('OTHER', 'Other'),
                ],
                max_length=30,
                verbose_name='Business Type'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='years_in_business',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Number of years the business has been operating',
                null=True,
                verbose_name='Years in Business'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_business_turnover',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Average monthly revenue from business operations',
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Monthly Business Turnover'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Next of Kin Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Next of Kin Phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_kin_relationship',
            field=models.CharField(
                blank=True,
                help_text="Relationship to the customer (e.g., Spouse, Parent, Sibling)",
                max_length=50,
                verbose_name='Next of Kin Relationship'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_name',
            field=models.CharField(
                blank=True,
                help_text='Name of the person who referred this customer',
                max_length=200,
                verbose_name='Referred By'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='mpesa_number',
            field=models.CharField(
                blank=True,
                help_text='Must start with 254 e.g. 254712345678',
                max_length=15,
                verbose_name='M-Pesa Number'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PARTIAL', 'Partially Complete'),
                    ('COMPLETE', 'Complete — Awaiting Verification'),
                    ('VERIFIED', 'Verified'),
                    ('REJECTED', 'Rejected'),
                ],
                db_index=True,
                default='PENDING',
                help_text='Enhanced KYC status matching Odoo\'s 5-state system',
                max_length=20,
                verbose_name='KYC Status'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_score',
            field=models.PositiveIntegerField(
                default=0,
                help_text='0-100 internal credit score assigned by the credit team',
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name='Internal Credit Score'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_rating',
            field=models.CharField(
                blank=True,
                choices=[
                    ('LOW', 'Low Risk'),
                    ('MEDIUM', 'Medium Risk'),
                    ('HIGH', 'High Risk'),
                    ('VERY_HIGH', 'Very High Risk'),
                ],
                help_text='Customer risk assessment category',
                max_length=20,
                verbose_name='Risk Rating'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, help_text='Customer account status', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the customer', verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='county_id',
            field=models.ForeignKey(
                blank=True,
                help_text='County selection (hierarchical)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='customers',
                to='loans.county'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_county_id',
            field=models.ForeignKey(
                blank=True,
                help_text='Sub-County selection (hierarchical)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='customers',
                to='loans.subcounty'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='ward_id',
            field=models.ForeignKey(
                blank=True,
                help_text='Ward selection (hierarchical)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='customers',
                to='loans.ward'
            ),
        ),
        
        # Update employment status choices (add BUSINESS_OWNER)
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(
                choices=[
                    ('EMPLOYED', 'Employed'),
                    ('SELF_EMPLOYED', 'Self Employed'),
                    ('BUSINESS_OWNER', 'Business Owner'),
                    ('UNEMPLOYED', 'Unemployed'),
                    ('RETIRED', 'Retired'),
                ],
                default='EMPLOYED',
                max_length=20,
                verbose_name='Employment Status (Odoo Alignment)'
            ),
        ),
        
        # Update county field to be legacy (hierarchical support added separately)
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='County (Legacy)'),
        ),
        
        # ========================================
        # Loan Application Model Enhancements
        # ========================================
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('SUBMITTED', 'Submitted'),
                    ('UNDER_REVIEW', 'Under Review'),
                    ('CREDIT_ANALYSIS', 'Credit Analysis'),
                    ('PENDING_APPROVAL', 'Pending Approval'),
                    ('APPROVED', 'Approved'),
                    ('DEFERRED', 'Deferred'),
                    ('EMPLOYER_VERIFICATION', 'Employer Verification'),
                    ('GUARANTOR_CONFIRMATION', 'Guarantor Confirmation'),
                    ('DISBURSED', 'Disbursed'),
                    ('DECLINED', 'Declined'),
                    ('REJECTED', 'Rejected'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='DRAFT',
                max_length=25,
                verbose_name='Application Status'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_analysis_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Credit Analysis At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pending_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pending Approval At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employer_verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Employer Verification At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Guarantor Confirmation At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='deferred_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deferred At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='declined_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Declined At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='conditions_of_approval',
            field=models.TextField(
                blank=True,
                help_text='Any special conditions that must be met before disbursement',
                verbose_name='Conditions of Approval'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Employer Name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status_reason',
            field=models.CharField(
                blank=True,
                help_text='Reason for deferral or decline',
                max_length=200,
                verbose_name='Status Reason'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='estimated_total_interest',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Calculated total interest over loan tenure',
                max_digits=12,
                null=True,
                verbose_name='Estimated Total Interest'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='estimated_total_fees',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Calculated total fees (processing, insurance, etc.)',
                max_digits=12,
                null=True,
                verbose_name='Estimated Total Fees'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='estimated_total_repayable',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Principal + Interest + Fees',
                max_digits=12,
                null=True,
                verbose_name='Estimated Total Repayable'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='net_disbursement_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Amount to be paid to customer after deducting fees',
                max_digits=12,
                null=True,
                verbose_name='Net Disbursement'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='application_progress',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Progress percentage through application stages',
                verbose_name='Application Progress'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='has_guarantor_block',
            field=models.BooleanField(
                default=False,
                help_text='Application blocked due to missing guarantor requirements',
                verbose_name='Guarantor Block'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='has_collateral_block',
            field=models.BooleanField(
                default=False,
                help_text='Application blocked due to missing collateral requirements',
                verbose_name='Collateral Block'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='risk_score',
            field=models.FloatField(
                default=0.0,
                help_text='Computed risk score based on customer assessment',
                verbose_name='Credit Risk Score'
            ),
        ),
        
        # ========================================
        # Loan Product Model Enhancements
        # ========================================
        migrations.AddField(
            model_name='loanproduct',
            name='color',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Color used in Kanban and Tree views',
                verbose_name='Color Index'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='requires_employer',
            field=models.BooleanField(
                default=False,
                help_text='Show employer, job title, and payslip fields on the application',
                verbose_name='Requires Employer Details'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_guarantors',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Minimum number of confirmed guarantors required before disbursement',
                verbose_name='Minimum Guarantors'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='requires_collateral',
            field=models.BooleanField(
                default=False,
                help_text='Show collateral tab and enforce collateral pledge before disbursement',
                verbose_name='Requires Collateral'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='requires_business_info',
            field=models.BooleanField(
                default=False,
                help_text='Show business name, registration, type, and revenue fields',
                verbose_name='Requires Business Information'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='requires_payslip',
            field=models.BooleanField(
                default=False,
                help_text='Enforce payslip document upload before submission',
                verbose_name='Requires Payslip / Proof of Income'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='requires_business_reg',
            field=models.BooleanField(
                default=False,
                help_text='Enforce business registration certificate upload',
                verbose_name='Requires Business Registration Docs'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='auto_approve_score_threshold',
            field=models.PositiveIntegerField(
                default=85,
                help_text='Applications with a credit score above this threshold can be auto-approved',
                verbose_name='Auto-Approve Score Threshold'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='auto_disburse',
            field=models.BooleanField(
                default=False,
                help_text='If ticked, approved applications will automatically trigger a B2C API call to disburse funds instantly',
                verbose_name='Auto-Disburse via M-Pesa B2C'
            ),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='provision_rate',
            field=models.DecimalField(
                default=1.0,
                decimal_places=2,
                help_text='Base provisioning rate for Normal loans. Substandard/Doubtful/Loss rates are fixed by company policy',
                max_digits=5,
                verbose_name='Default Provisioning Rate (%)'
            ),
        ),
        
        # ========================================
        # Indexes
        # ========================================
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status', '-created_at'], name='loans_cust_kyc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['active'], name='loans_cust_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['credit_score'], name='loans_cust_credit_score_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['risk_rating'], name='loans_cust_risk_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['county_id'], name='loans_cust_county_id_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['sub_county_id'], name='loans_cust_sub_county_id_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['ward_id'], name='loans_cust_ward_id_idx'),
        ),
    ]