# Generated by Django for Phase 2 - Missing Model Implementation

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_phase1_odoo_alignment'),
    ]

    operations = [
        # ========================================
        # Employer Model
        # ========================================
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Employer Name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('company_registration_number', models.CharField(blank=True, help_text='Business registration number for the employer', max_length=100, verbose_name='Company Registration Number')),
                ('tax_pin', models.CharField(blank=True, help_text='Kenya Revenue Authority PIN', max_length=20, verbose_name='Tax PIN')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry/Sector')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'ordering': ['name'],
                'db_table': 'employers',
            },
        ),
        
        # ========================================
        # Loan Status Reason Model
        # ========================================
        migrations.CreateModel(
            name='LoanStatusReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DEFERRED', 'Deferred'), ('DECLINED', 'Declined')], help_text='Status reason category (deferred or declined)', max_length=20, verbose_name='Category')),
                ('reason', models.CharField(max_length=200, verbose_name='Reason')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Loan Status Reason',
                'verbose_name_plural': 'Loan Status Reasons',
                'ordering': ['category', 'reason'],
                'db_table': 'loan_status_reasons',
            },
        ),
        
        # ========================================
        # Customer Tag Model
        # ========================================
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('color', models.PositiveIntegerField(default=0, help_text='Color used in Kanban and Tree views', verbose_name='Color Index')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer Tag',
                'verbose_name_plural': 'Customer Tags',
                'ordering': ['name'],
                'db_table': 'customer_tags',
            },
        ),
        
        # ========================================
        # Fee Template Model
        # ========================================
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=100, verbose_name='Fee Name')),
                ('fee_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Loan Amount')], default='FIXED', max_length=20, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage (0-100)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this fee is mandatory for all applications', verbose_name='Mandatory')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_templates', to='loans.loanproduct', verbose_name='Loan Product')),
            ],
            options={
                'verbose_name': 'Fee Template',
                'verbose_name_plural': 'Fee Templates',
                'ordering': ['loan_product', 'fee_name'],
                'db_table': 'fee_templates',
            },
        ),
        
        # ========================================
        # Fee Line Model
        # ========================================
        migrations.CreateModel(
            name='FeeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=100, verbose_name='Fee Name')),
                ('fee_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Loan Amount')], max_length=20, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fee_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_lines', to='loans.feetemplate', verbose_name='Fee Template')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_lines', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Fee Line',
                'verbose_name_plural': 'Fee Lines',
                'ordering': ['loan_application', 'fee_name'],
                'db_table': 'fee_lines',
            },
        ),
        
        # ========================================
        # Guarantor Model
        # ========================================
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('id_number', models.CharField(max_length=50, verbose_name='ID/Passport Number')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, verbose_name='Email Address')),
                ('relationship', models.CharField(help_text='e.g., Spouse, Parent, Sibling, Friend', max_length=50, verbose_name='Relationship to Borrower')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='Employer')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Income')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('confirmation_code', models.CharField(blank=True, help_text='Unique code sent to guarantor for confirmation', max_length=50, unique=True, verbose_name='Confirmation Code')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('confirmed_via', models.CharField(blank=True, help_text='Method of confirmation (SMS, Email, In-Person)', max_length=20, verbose_name='Confirmed Via')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('id_document_file', models.FileField(blank=True, upload_to='guarantor_documents/id/%Y/%m/%d/', verbose_name='ID Document')),
                ('payslip_file', models.FileField(blank=True, upload_to='guarantor_documents/payslips/%Y/%m/%d/', verbose_name='Payslip')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Guarantor',
                'verbose_name_plural': 'Guarantors',
                'ordering': ['-created_at'],
                'db_table': 'guarantors',
            },
        ),
        
        # ========================================
        # Collateral Model
        # ========================================
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('LAND', 'Land'), ('BUILDING', 'Building'), ('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment'), ('INVENTORY', 'Inventory'), ('RECEIVABLES', 'Receivables'), ('OTHER', 'Other')], max_length=30, verbose_name='Collateral Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Value')),
                ('valuation_date', models.DateField(blank=True, null=True, verbose_name='Valuation Date')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Physical Location')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PLEDGED', 'Pledged'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('title_deed_file', models.FileField(blank=True, upload_to='collateral_documents/title_deeds/%Y/%m/%d/', verbose_name='Title Deed')),
                ('insurance_certificate_file', models.FileField(blank=True, upload_to='collateral_documents/insurance/%Y/%m/%d/', verbose_name='Insurance Certificate')),
                ('valuation_report_file', models.FileField(blank=True, upload_to='collateral_documents/valuations/%Y/%m/%d/', verbose_name='Valuation Report')),
                ('pledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Pledged At')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Released At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loanapplication', verbose_name='Loan Application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_collaterals', to='loans.user')),
            ],
            options={
                'verbose_name': 'Collateral',
                'verbose_name_plural': 'Collaterals',
                'ordering': ['-created_at'],
                'db_table': 'collaterals',
            },
        ),
        
        # ========================================
        # KYC Provider Model
        # ========================================
        migrations.CreateModel(
            name='KYCProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Provider Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API Endpoint')),
                ('api_key', models.CharField(blank=True, max_length=100, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=100, verbose_name='API Secret')),
                ('provider_type', models.CharField(blank=True, help_text='e.g., IDValidate, CRB, CreditInfo', max_length=50, verbose_name='Provider Type')),
                ('confidence_threshold', models.PositiveIntegerField(default=80, help_text='Minimum confidence score to accept verification', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Confidence Threshold (%)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'KYC Provider',
                'verbose_name_plural': 'KYC Providers',
                'ordering': ['name'],
                'db_table': 'kyc_providers',
            },
        ),
        
        # ========================================
        # Add Foreign Key Relationships to Customer
        # ========================================
        migrations.AddField(
            model_name='customer',
            name='employer_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employees',
                to='loans.employer',
                verbose_name='Employer'
            ),
        ),
        
        # ========================================
        # Add ManyToMany Relationship for Customer Tags
        # ========================================
        migrations.AddField(
            model_name='customer',
            name='tag_ids',
            field=models.ManyToManyField(
                blank=True,
                related_name='customers',
                to='loans.customertag',
                verbose_name='Tags'
            ),
        ),
        
        # ========================================
        # Add Foreign Key Relationships to Loan Application
        # ========================================
        migrations.AddField(
            model_name='loanapplication',
            name='employer_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='loan_applications',
                to='loans.employer',
                verbose_name='Employer'
            ),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status_reason_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='loan_applications',
                to='loans.loanstatusreason',
                verbose_name='Status Reason'
            ),
        ),
        
        # ========================================
        # Update status_reason field to be legacy
        # ========================================
        migrations.AlterField(
            model_name='loanapplication',
            name='status_reason',
            field=models.CharField(
                blank=True,
                help_text='Reason for deferral or decline (legacy - use status_reason_id)',
                max_length=200,
                verbose_name='Status Reason (Legacy)'
            ),
        ),
        
        # ========================================
        # Indexes
        # ========================================
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['name'], name='loans_empl_name_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['is_active'], name='loans_empl_active_idx'),
        ),
        migrations.AddIndex(
            model_name='loanstatusreason',
            index=models.Index(fields=['category', 'is_active'], name='loans_lsr_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='loanstatusreason',
            index=models.Index(fields=['is_active'], name='loans_lsr_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['name'], name='loans_ctag_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['is_active'], name='loans_ctag_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['loan_product', 'is_active'], name='loans_ft_prod_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['fee_type'], name='loans_ft_type_idx'),
        ),
        migrations.AddIndex(
            model_name='feeline',
            index=models.Index(fields=['loan_application'], name='loans_fl_app_idx'),
        ),
        migrations.AddIndex(
            model_name='feeline',
            index=models.Index(fields=['is_paid'], name='loans_fl_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['loan_application', 'status'], name='loans_guar_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['status'], name='loans_guar_status_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['id_number'], name='loans_guar_id_num_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['loan_application', 'status'], name='loans_coll_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['status'], name='loans_coll_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['collateral_type'], name='loans_coll_type_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprovider',
            index=models.Index(fields=['is_active'], name='loans_kycp_active_idx'),
        ),
    ]