# Generated by Django 5.2.12 on 2026-07-29 08:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_phase2_missing_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collateral',
            new_name='collaterals_loan_ap_be646a_idx',
            old_name='loans_coll_app_status_idx',
        ),
        migrations.RenameIndex(
            model_name='collateral',
            new_name='collaterals_status_4384d7_idx',
            old_name='loans_coll_status_idx',
        ),
        migrations.RenameIndex(
            model_name='collateral',
            new_name='collaterals_collate_6c1d8a_idx',
            old_name='loans_coll_type_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_kyc_sta_f42c42_idx',
            old_name='loans_cust_kyc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_active_51d94a_idx',
            old_name='loans_cust_active_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_credit__b57905_idx',
            old_name='loans_cust_credit_score_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_risk_ra_f5cdac_idx',
            old_name='loans_cust_risk_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_county__cd1637_idx',
            old_name='loans_cust_county_id_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_sub_cou_350683_idx',
            old_name='loans_cust_sub_county_id_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_ward_id_e0eb74_idx',
            old_name='loans_cust_ward_id_idx',
        ),
        migrations.RenameIndex(
            model_name='customertag',
            new_name='customer_ta_name_f2cbd5_idx',
            old_name='loans_ctag_name_idx',
        ),
        migrations.RenameIndex(
            model_name='customertag',
            new_name='customer_ta_is_acti_75098e_idx',
            old_name='loans_ctag_active_idx',
        ),
        migrations.RenameIndex(
            model_name='employer',
            new_name='employers_name_a261b2_idx',
            old_name='loans_empl_name_idx',
        ),
        migrations.RenameIndex(
            model_name='employer',
            new_name='employers_is_acti_7130f1_idx',
            old_name='loans_empl_active_idx',
        ),
        migrations.RenameIndex(
            model_name='feeline',
            new_name='fee_lines_loan_ap_951ae2_idx',
            old_name='loans_fl_app_idx',
        ),
        migrations.RenameIndex(
            model_name='feeline',
            new_name='fee_lines_is_paid_795652_idx',
            old_name='loans_fl_paid_idx',
        ),
        migrations.RenameIndex(
            model_name='feetemplate',
            new_name='fee_templat_loan_pr_05a6c3_idx',
            old_name='loans_ft_prod_active_idx',
        ),
        migrations.RenameIndex(
            model_name='feetemplate',
            new_name='fee_templat_fee_typ_9aa729_idx',
            old_name='loans_ft_type_idx',
        ),
        migrations.RenameIndex(
            model_name='guarantor',
            new_name='guarantors_loan_ap_875ad7_idx',
            old_name='loans_guar_app_status_idx',
        ),
        migrations.RenameIndex(
            model_name='guarantor',
            new_name='guarantors_status_83465f_idx',
            old_name='loans_guar_status_idx',
        ),
        migrations.RenameIndex(
            model_name='guarantor',
            new_name='guarantors_id_numb_ecb60c_idx',
            old_name='loans_guar_id_num_idx',
        ),
        migrations.RenameIndex(
            model_name='kycprovider',
            new_name='kyc_provide_is_acti_d09be8_idx',
            old_name='loans_kycp_active_idx',
        ),
        migrations.RenameIndex(
            model_name='loanstatusreason',
            new_name='loan_status_categor_606690_idx',
            old_name='loans_lsr_cat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='loanstatusreason',
            new_name='loan_status_is_acti_6f6851_idx',
            old_name='loans_lsr_active_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='odoo_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last sync attempt to Odoo', null=True, verbose_name='Last Odoo Sync Attempt'),
        ),
        migrations.AddField(
            model_name='customer',
            name='odoo_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of sync attempts made to Odoo', verbose_name='Odoo Sync Attempts'),
        ),
        migrations.AddField(
            model_name='customer',
            name='odoo_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync to Odoo failed', verbose_name='Odoo Sync Error'),
        ),
        migrations.AddField(
            model_name='customer',
            name='odoo_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', help_text='Status of customer sync to Odoo', max_length=20, verbose_name='Odoo Sync Status'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='address',
            field=models.TextField(blank=True, verbose_name='Physical Address'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='liability_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum guaranteed amount (Odoo Alignment)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Liability Amount'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monthly Income'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='odoo_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last sync attempt to Odoo', null=True, verbose_name='Last Odoo Sync Attempt'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='odoo_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of sync attempts made to Odoo', verbose_name='Odoo Sync Attempts'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='odoo_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync to Odoo failed', verbose_name='Odoo Sync Error'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='odoo_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', help_text='Status of application sync to Odoo', max_length=20, verbose_name='Odoo Sync Status'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_document_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the corresponding alba.loan.document record in Odoo', null=True, verbose_name='Odoo Document ID'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_document_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', help_text='Verification status of the document in Odoo', max_length=20, verbose_name='Odoo Document State'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last sync attempt to Odoo', null=True, verbose_name='Last Odoo Sync At'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync to Odoo failed', verbose_name='Odoo Sync Error'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of document sync to Odoo', max_length=20, verbose_name='Odoo Sync Status'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Rejection reason from Odoo if rejected', verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kyc_verified',
            field=models.BooleanField(default=False, help_text='Legacy boolean field - use kyc_status for new implementations', verbose_name='KYC Verified (Legacy)'),
        ),
        migrations.AlterField(
            model_name='guarantorverification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_verifications', to='loans.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('bank_statement', 'Bank Statement'), ('payslip', 'Payslip'), ('employment_letter', 'Employment Letter'), ('business_registration', 'Business Registration'), ('kra_pin', 'KRA PIN Certificate'), ('utility_bill', 'Utility Bill'), ('title_deed', 'Title Deed'), ('valuation_report', 'Valuation Report'), ('insurance', 'Insurance Document'), ('contract', 'Contract'), ('guarantor_id', 'Guarantor ID'), ('other', 'Other')], max_length=30, verbose_name='Document Type'),
        ),
        migrations.AlterUniqueTogether(
            name='subcounty',
            unique_together={('county', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('sub_county', 'code')},
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['code'], name='counties_code_8c1899_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['is_active'], name='counties_is_acti_186417_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['county', 'is_active'], name='sub_countie_county__6900b0_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['code'], name='sub_countie_code_cdaa3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['sub_county', 'is_active'], name='wards_sub_cou_827da1_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['code'], name='wards_code_5a9eed_idx'),
        ),
    ]
