# Generated by Django 5.2.12 on 2026-08-10 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_rename_loans_coll_app_status_idx_collaterals_loan_ap_be646a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number', ''), _negated=True), fields=('reference_number',), name='unique_nonblank_reference_number'),
        ),
    ]
