# Generated by Django 5.2.12 on 2026-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_rename_loans_coll_app_status_idx_collaterals_loan_ap_be646a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocument',
            name='odoo_document_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the corresponding alba.loan.document record in Odoo', null=True, verbose_name='Odoo Document ID'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last sync attempt to Odoo', null=True, verbose_name='Last Odoo Sync At'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync to Odoo failed', verbose_name='Odoo Sync Error'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='odoo_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of document sync to Odoo', max_length=20, verbose_name='Odoo Sync Status'),
        ),
    ]
