# Generated by Django 5.2.17 on 2026-08-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loanrepayment_unique_nonblank_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_guarantor_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the corresponding alba.guarantor record in Odoo', null=True, verbose_name='Odoo Guarantor (Master) ID'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_guarantor_status',
            field=models.CharField(blank=True, help_text="Raw alba.loan.guarantor.status value from Odoo (e.g. confirmation_sent, pledged, liability) — Odoo's workflow has more states than this model's coarse status field can represent.", max_length=30, verbose_name='Odoo Guarantor Status'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Odoo Sync Attempt'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_loan_guarantor_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the corresponding alba.loan.guarantor record in Odoo', null=True, verbose_name='Odoo Loan Guarantor ID'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of sync attempts made to Odoo', verbose_name='Odoo Sync Attempts'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync to Odoo failed', verbose_name='Odoo Sync Error'),
        ),
        migrations.AddField(
            model_name='guarantorverification',
            name='odoo_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', help_text="Status of this guarantor's sync to Odoo", max_length=20, verbose_name='Odoo Sync Status'),
        ),
        migrations.DeleteModel(
            name='Guarantor',
        ),
    ]
