# Generated by Django 5.2.12 on 2026-07-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loandocument_odoo_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocument',
            name='odoo_document_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', help_text='Verification status of the document in Odoo', max_length=20, verbose_name='Odoo Document State'),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Rejection reason from Odoo if rejected', verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('bank_statement', 'Bank Statement'), ('payslip', 'Payslip'), ('employment_letter', 'Employment Letter'), ('kra_pin', 'KRA PIN Certificate'), ('guarantor_id', 'Guarantor ID'), ('other', 'Other')], max_length=30, verbose_name='Document Type'),
        ),
    ]
