# Generated by Django 5.2.12 on 2026-07-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_loandocument_odoo_document_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('bank_statement', 'Bank Statement'), ('payslip', 'Payslip'), ('employment_letter', 'Employment Letter'), ('business_registration', 'Business Registration'), ('kra_pin', 'KRA PIN Certificate'), ('utility_bill', 'Utility Bill'), ('title_deed', 'Title Deed'), ('valuation_report', 'Valuation Report'), ('insurance', 'Insurance Document'), ('contract', 'Contract'), ('guarantor_id', 'Guarantor ID'), ('other', 'Other')], max_length=30, verbose_name='Document Type'),
        ),
    ]
