# Generated by Django 5.2.17 on 2026-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_guarantor_sync_and_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='odoo_collateral_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the corresponding alba.collateral record in Odoo', null=True, verbose_name='Odoo Collateral ID'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='odoo_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Odoo Sync Attempt'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='odoo_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of sync attempts made to Odoo', verbose_name='Odoo Sync Attempts'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='odoo_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync to Odoo failed', verbose_name='Odoo Sync Error'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='odoo_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', help_text="Status of this collateral's sync to Odoo", max_length=20, verbose_name='Odoo Sync Status'),
        ),
    ]
