# Generated by Django 5.2.17 on 2026-08-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_collateral_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='face_encoding_data',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='face_scan_date',
        ),
    ]
