# Generated by Django 5.2.17 on 2026-08-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_remove_dead_face_encoding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='odoo_collateral_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the corresponding alba.collateral record in Odoo', null=True, unique=True, verbose_name='Odoo Collateral ID'),
        ),
    ]
