# Generated by Django 5.2.12 on 2026-08-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_alter_loandocument_document_type'),
        ('loans', '0018_remove_dead_face_encoding_fields'),
    ]

    operations = [
    ]
