# Generated by Django 5.2.12 on 2026-08-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_alter_collateral_odoo_collateral_id'),
        ('loans', '0019_merge_20260811_1432'),
    ]

    operations = [
    ]
