# Generated by Django 5.2.17 on 2026-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_merge_20260818_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employer_contact',
            field=models.CharField(blank=True, max_length=30, verbose_name='Employer Contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=50, verbose_name='Nationality'),
        ),
    ]
