# -*- coding: utf-8 -*-

from . import (
    # Base models first (no dependencies)
    loan_product,
    employer,
    kyc_provider,
    location,
    customer_tag,
    currency_config,
    business_sector,
    loan_status_reason,
    customer,
    mpesa_config,
    loan_document,
    guarantor,
    collateral,
    credit_score,
    # Models with dependencies
    loan_application,
    loan,
    loan_repayment,
    repayment_schedule,
    loan_rules,
    collections,
    approval_workflow,
    loan_disbursement_split,
    credit_life_insurance,
    investor,
    mpesa_transaction,
    report_financials,
    loan_dashboard,
    res_partner,
    # Loan modifications
    loan_topup,
    loan_partial_payoff,
    loan_payment_holiday,
    loan_refinance,
    loan_consolidation,
    notification_hooks,
)
