# -*- coding: utf-8 -*-
from odoo import api, fields, models


class AlbaRepaymentScheduleBatch(models.Model):
    _name = "alba.repayment.schedule.batch"
    _description = "Repayment Schedule Batch / Version"
    _order = "generated_on desc, id desc"

    name = fields.Char(string="Batch Name", required=True, default=lambda self: self._default_name())
    loan_id = fields.Many2one("alba.loan", string="Loan", required=True, ondelete="cascade", index=True)
    generated_on = fields.Datetime(string="Generated On", default=fields.Datetime.now)
    generated_by = fields.Many2one("res.users", string="Generated By", default=lambda self: self.env.uid)
    state = fields.Selection([('active','Active'), ('archived','Archived')], string="State", default='active')
    notes = fields.Text(string="Notes")

    def _default_name(self):
        return self.env['ir.sequence'].next_by_code('alba.repayment.schedule.batch.seq') or 'Schedule Batch'

    @api.model
    def create_initial_batches_for_existing_loans(self):
        """Create an initial active batch and attach existing repayment schedule lines.

        This is a helper migration utility you can call from a server shell:
            env['alba.repayment.schedule.batch'].create_initial_batches_for_existing_loans()
        """
        Loan = self.env['alba.loan']
        Schedule = self.env['alba.repayment.schedule']
        created = 0
        for loan in Loan.search([]):
            lines = Schedule.search([('loan_id', '=', loan.id)])
            if not lines:
                continue
            batch = self.create({
                'loan_id': loan.id,
                'notes': 'Initial batch created by migration helper',
            })
            lines.write({'batch_id': batch.id})
            created += 1
        return created
