# Generated by Django 5.0.2 on 2026-03-01 13:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier (e.g., 1010, 2100, 4010)', max_length=20, unique=True, verbose_name='Account Code')),
                ('name', models.CharField(help_text='Descriptive account name', max_length=200, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='Primary classification for financial reporting', max_length=20, verbose_name='Account Type')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot be used in new transactions', verbose_name='Active')),
                ('is_control', models.BooleanField(default=False, help_text='Control accounts cannot have direct postings (summary only)', verbose_name='Control Account')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Real-time account balance (updated on transaction posting)', max_digits=15, verbose_name='Current Balance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchical reporting', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'accounting_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(max_length=100, unique=True, verbose_name='Statement Number')),
                ('statement_date', models.DateField(verbose_name='Statement Date')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Opening Balance')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Closing Balance')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Reconciliation'), ('RECONCILED', 'Reconciled'), ('PARTIAL', 'Partially Reconciled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('import_file', models.CharField(blank=True, max_length=500, verbose_name='Import File')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Imported At')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciled At')),
                ('bank_account', models.ForeignKey(help_text='Bank account from Chart of Accounts', limit_choices_to={'account_type': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='accounting.account')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_statements', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'db_table': 'accounting_bank_statements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Period Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_closed', models.BooleanField(default=False, help_text='Closed periods cannot have new transactions', verbose_name='Closed')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'db_table': 'accounting_fiscal_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(help_text='Auto-generated unique identifier', max_length=50, unique=True, verbose_name='Entry Number')),
                ('entry_type', models.CharField(choices=[('STANDARD', 'Standard Entry'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('INTEREST_ACCRUAL', 'Interest Accrual'), ('FEE_RECOGNITION', 'Fee Recognition'), ('PENALTY_ACCRUAL', 'Penalty Accrual'), ('WRITE_OFF', 'Loan Write-Off'), ('PAYROLL', 'Payroll Entry'), ('DEPRECIATION', 'Depreciation'), ('BANK_TRANSACTION', 'Bank Transaction'), ('ADJUSTMENT', 'Adjustment Entry')], default='STANDARD', max_length=30, verbose_name='Entry Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when transaction occurred', verbose_name='Transaction Date')),
                ('reference', models.CharField(blank=True, help_text='External reference (invoice number, loan ID, etc.)', max_length=200, verbose_name='Reference')),
                ('description', models.TextField(help_text='Detailed explanation of the transaction', verbose_name='Description')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Debit')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Credit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='loans.loan')),
                ('loan_repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='loans.loanrepayment')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversed_entry', models.ForeignKey(blank=True, help_text='Original entry that this entry reverses', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversing_entries', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'accounting_journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('FEE', 'Bank Fee'), ('INTEREST', 'Interest'), ('TRANSFER', 'Transfer')], max_length=20, verbose_name='Type')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Reference')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for deposits, negative for withdrawals', max_digits=15, verbose_name='Amount')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciled')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciled At')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankstatement')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL)),
                ('matched_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_transactions', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'db_table': 'accounting_bank_transactions',
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to debit (increase assets/expenses)', max_digits=15, verbose_name='Debit Amount')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to credit (increase liabilities/equity/revenue)', max_digits=15, verbose_name='Credit Amount')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Line Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('account', models.ForeignKey(help_text='Account to be debited or credited', on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'db_table': 'accounting_journal_lines',
                'ordering': ['journal_entry', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_4dfc77_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_96248c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_8b7038_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='accounting__entry_n_6a4196_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_0a42cd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='accounting__status_037e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type'], name='accounting__entry_t_13fc44_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['journal_entry', 'account'], name='accounting__journal_f9fd5d_idx'),
        ),
    ]
