# Generated by Django 5.0.2 on 2026-03-01 15:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('is_base', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center_code',
            field=models.CharField(blank=True, db_index=True, help_text='Cost center code for departmental tracking', max_length=50, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, help_text='Project code for job costing', max_length=50, verbose_name='Project Code'),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cost_centers', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.costcenter')),
            ],
            options={
                'db_table': 'accounting_cost_centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LAND', 'Land'), ('BUILDINGS', 'Buildings'), ('VEHICLES', 'Vehicles'), ('EQUIPMENT', 'Equipment'), ('FURNITURE', 'Furniture & Fixtures'), ('COMPUTERS', 'Computers & IT Equipment')], db_index=True, max_length=50)),
                ('purchase_date', models.DateField(db_index=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('useful_life_years', models.DecimalField(decimal_places=1, max_digits=5)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance')], default='STRAIGHT_LINE', max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPOSED', 'Disposed'), ('FULLY_DEPRECIATED', 'Fully Depreciated')], db_index=True, default='ACTIVE', max_length=20)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_depreciation_assets', to='accounting.account')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.costcenter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fixed_assets', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodian_assets', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_assets', to='accounting.account')),
            ],
            options={
                'db_table': 'accounting_fixed_assets',
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNING', max_length=20)),
                ('budgeted_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('budgeted_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounting.costcenter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('CBK', 'Central Bank of Kenya'), ('MANUAL', 'Manual Entry'), ('API', 'External API')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exchange_rates', to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='accounting.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='accounting.currency')),
            ],
            options={
                'db_table': 'accounting_exchange_rates',
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depreciation_expense', models.DecimalField(decimal_places=2, max_digits=20)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='accounting.journalentry')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedules', to='accounting.fixedasset')),
            ],
            options={
                'db_table': 'accounting_depreciation_schedules',
                'ordering': ['fixed_asset', 'period_end_date'],
                'unique_together': {('fixed_asset', 'period_end_date')},
            },
        ),
    ]
