# Generated by Django 5.0.2 on 2026-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_currency_journalline_cost_center_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='cost_center_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cost center code for departmental tracking', max_length=50, verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Project code for job costing', max_length=50, verbose_name='Project Code'),
        ),
    ]
